[project]
name = "malange"
version = "1.0.0.dev1"
description = "An extensible, modular, and open-source application framework."
readme = "README.md"
authors = [
    { name = "derweltgeist", email = "anoki.blazed@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "malange-core",
    "malange-web"
]

[project.scripts]
malange = "malange:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "packages/malange_core",
    "packages/malange_web",
]

[tool.uv.sources]
malange-core = { workspace = true }
malange-web  = { workspace = true }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
